### ISSUE TITLE
The --remember-user-session flag stopped remembering the session in v0.9.1

### ISSUE THREAD

**Issue by alerque** [apognu/tuigreet#145]
Possibly as an unexpected side effect of #141, the current version has stopped remembering the last session used. My systems are now booting up into the first session in the alphabetical list, not the one I last used. 

```toml
[default_session]
command = "tuigreet --issue --time --user-menu --remember --remember-user-session --asterisks"
```

Given that it does remember the last user, not also remembering the last session is ridiculous. I would expect not only the user but also the last session used to be already selected on boot and just waiting for my password.
